# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.circularProgressBarBase = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBarBase.setGeometry(QtCore.QRect(20, 50, 391, 391))
        self.circularProgressBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBarBase.setObjectName("circularProgressBarBase")
        self.circularProgress = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularProgress.setGeometry(QtCore.QRect(10, 10, 371, 371))
        self.circularProgress.setStyleSheet("QFrame{\n"
"    border-radius: 180px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:270, stop:0.749 rgba(255, 0, 127, 0), stop:0.75 rgba(255, 0, 0, 255));\n"
"}\n"
"\n"
"")
        self.circularProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgress.setObjectName("circularProgress")
        self.circularBg = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 371, 371))
        self.circularBg.setStyleSheet("QFrame{\n"
"    border-radius: 180px;\n"
"    background-color: rgba(77, 77, 127, 120);\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg.setObjectName("circularBg")
        self.container = QtWidgets.QFrame(self.circularProgressBarBase)
        self.container.setGeometry(QtCore.QRect(25, 25, 341, 341))
        self.container.setStyleSheet("QFrame{\n"
"    border-radius: 165px;\n"
"    background-color: rgb(77, 77, 127);\n"
"}")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.layoutWidget = QtWidgets.QWidget(self.container)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 201, 262))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelUnit = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(60)
        self.labelUnit.setFont(font)
        self.labelUnit.setAutoFillBackground(False)
        self.labelUnit.setStyleSheet("QLabel{\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(112, 112, 184);\n"
"    color: #FFFFFF\n"
"}")
        self.labelUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnit.setObjectName("labelUnit")
        self.gridLayout.addWidget(self.labelUnit, 3, 0, 1, 1)
        self.labelValue = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(72)
        self.labelValue.setFont(font)
        self.labelValue.setAutoFillBackground(False)
        self.labelValue.setStyleSheet("background-color: none;\n"
"color: #FFFFFF")
        self.labelValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValue.setObjectName("labelValue")
        self.gridLayout.addWidget(self.labelValue, 2, 0, 1, 1)
        self.labelTitle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setAutoFillBackground(False)
        self.labelTitle.setStyleSheet("background-color: none;\n"
"color: #FFFFFF")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 1, 0, 1, 1)
        self.circularBg.raise_()
        self.circularProgress.raise_()
        self.container.raise_()
        self.Bars = QtWidgets.QFrame(self.centralwidget)
        self.Bars.setGeometry(QtCore.QRect(430, 80, 341, 351))
        self.Bars.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Bars.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bars.setObjectName("Bars")
        self.SoC = QtWidgets.QFrame(self.Bars)
        self.SoC.setGeometry(QtCore.QRect(0, 20, 341, 141))
        self.SoC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SoC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SoC.setObjectName("SoC")
        self.Var_SoCVal = QtWidgets.QLabel(self.SoC)
        self.Var_SoCVal.setGeometry(QtCore.QRect(10, 10, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(27)
        self.Var_SoCVal.setFont(font)
        self.Var_SoCVal.setAutoFillBackground(False)
        self.Var_SoCVal.setStyleSheet("QLabel{\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(77, 77, 127);\n"
"    color: #FFFFFF\n"
"}")
        self.Var_SoCVal.setAlignment(QtCore.Qt.AlignCenter)
        self.Var_SoCVal.setObjectName("Var_SoCVal")
        self.frame_5 = QtWidgets.QFrame(self.SoC)
        self.frame_5.setGeometry(QtCore.QRect(180, -20, 131, 101))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setGeometry(QtCore.QRect(0, 30, 121, 61))
        self.frame.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(-10, 0, 71, 41))
        self.frame_4.setStyleSheet("background-color: rgb(112, 112, 184);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setGeometry(QtCore.QRect(112, 40, 20, 41))
        self.frame_3.setStyleSheet("background-color: rgb(77, 77, 127);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Var_SoCBar = QtWidgets.QProgressBar(self.SoC)
        self.Var_SoCBar.setGeometry(QtCore.QRect(10, 100, 321, 31))
        self.Var_SoCBar.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: #CD96CD;\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}")
        self.Var_SoCBar.setProperty("value", 90)
        self.Var_SoCBar.setTextVisible(False)
        self.Var_SoCBar.setObjectName("Var_SoCBar")
        self.frame_6 = QtWidgets.QFrame(self.SoC)
        self.frame_6.setGeometry(QtCore.QRect(9, 90, 111, 41))
        self.frame_6.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_13 = QtWidgets.QFrame(self.SoC)
        self.frame_13.setGeometry(QtCore.QRect(120, 90, 41, 41))
        self.frame_13.setStyleSheet("background-color: rgb(255, 163, 72);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(60, 50, 120, 51))
        self.frame_14.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_17 = QtWidgets.QFrame(self.SoC)
        self.frame_17.setGeometry(QtCore.QRect(160, 90, 171, 41))
        self.frame_17.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setGeometry(QtCore.QRect(60, 50, 120, 51))
        self.frame_18.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.Var_SoCVal.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_13.raise_()
        self.frame_17.raise_()
        self.Var_SoCBar.raise_()
        self.Batt = QtWidgets.QFrame(self.Bars)
        self.Batt.setGeometry(QtCore.QRect(0, 150, 341, 131))
        self.Batt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Batt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Batt.setObjectName("Batt")
        self.TBTitle = QtWidgets.QLabel(self.Batt)
        self.TBTitle.setGeometry(QtCore.QRect(10, 30, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(20)
        self.TBTitle.setFont(font)
        self.TBTitle.setAutoFillBackground(False)
        self.TBTitle.setStyleSheet("QLabel{\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(77, 77, 127);\n"
"    color: #FFFFFF\n"
"}")
        self.TBTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.TBTitle.setObjectName("TBTitle")
        self.Var_SoCBar_3 = QtWidgets.QProgressBar(self.Bars)
        self.Var_SoCBar_3.setGeometry(QtCore.QRect(10, 270, 321, 31))
        self.Var_SoCBar_3.setAutoFillBackground(False)
        self.Var_SoCBar_3.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: #CD96CD;\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}")
        self.Var_SoCBar_3.setMinimum(0)
        self.Var_SoCBar_3.setProperty("value", 50)
        self.Var_SoCBar_3.setTextVisible(False)
        self.Var_SoCBar_3.setObjectName("Var_SoCBar_3")
        self.frame_7 = QtWidgets.QFrame(self.Bars)
        self.frame_7.setGeometry(QtCore.QRect(220, 260, 111, 41))
        self.frame_7.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.frame_8.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.frame_9.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(60, 50, 120, 51))
        self.frame_10.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_11 = QtWidgets.QFrame(self.Bars)
        self.frame_11.setGeometry(QtCore.QRect(180, 260, 41, 41))
        self.frame_11.setStyleSheet("background-color: rgb(255, 163, 72);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(60, 50, 120, 51))
        self.frame_12.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_15 = QtWidgets.QFrame(self.Bars)
        self.frame_15.setGeometry(QtCore.QRect(10, 260, 171, 41))
        self.frame_15.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setGeometry(QtCore.QRect(60, 50, 120, 51))
        self.frame_16.setStyleSheet("color: rgb(224, 27, 36);\n"
"background-color: rgb(224, 27, 36);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.SoC.raise_()
        self.Batt.raise_()
        self.frame_7.raise_()
        self.frame_11.raise_()
        self.frame_15.raise_()
        self.Var_SoCBar_3.raise_()
        self.Bars.raise_()
        self.circularProgressBarBase.raise_()
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.labelUnit.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">RPM</span></p></body></html>"))
        self.labelValue.setText(_translate("SplashScreen", "100"))
        self.labelTitle.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:600; color:#9b9bff;\">SPEED</span></p></body></html>"))
        self.Var_SoCVal.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-size:28pt;\">99 %</span></p></body></html>"))
        self.TBTitle.setText(_translate("SplashScreen", "<html><head/><body><p>Battery Temperature</p></body></html>"))
